### PR TITLE
Adds `devicePixelRatio` in `PageMetrics`.

### PR DESCRIPTION
**Pull request by chaudharydeepanshu**
Added `devicePixelRatio: WidgetsBinding.instance.window.devicePixelRatio` in `PageMetrics()` due to the recent changes in Flutter master.

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
we will fix it after stable

**Comment by delfme** [comment]
I did same fix too the same day the issue occurred, forgot to raise a PR 👍

Can I suggest to make plugin compile on master? 95% of team code on master because, as strange as it may sound, stable channel is too buggy and miss many needed features

**Comment by snoopdoggy322** [comment]
It seems to me that with the release of 3.7, this PR is very relevant

**Comment by zmtzawqlp** [comment]
I still not see this change in stable 3.7.0

**Comment by Eimji** [comment]
Still no devicePixelRatio in 3.7.1, I come back to stable now.

**Comment by chaudharydeepanshu** [comment]
> Still no devicePixelRatio in 3.7.1, I come back to stable now.

I guess flutter may make that change in the next release.  So, either you can wait for a stable release or you can use the fork which is what I'm doing for now.

**Comment by Alijaaan** [comment]
Unfortunately the error is still exists in v7.0.0 and when I use the forked repo I got another error:
.../AppData/Local/Pub/Cache/git/extended_image-2b3eee49bbc0c055f1148eceea9ef0e1a3f48843/lib/src/gesture_detector/drag.dart(145,3): error GB23DA612: The superclass, 'OneSequenceGestureRecognizer with DragGestureRecognizerMixin', has no unnamed constructor that takes no arguments.

Am I doing something wrong?

**Comment by chaudharydeepanshu** [comment]
> Unfortunately the error is still exists in v7.0.0 and when I use the forked repo I got another error: .../AppData/Local/Pub/Cache/git/extended_image-2b3eee49bbc0c055f1148eceea9ef0e1a3f48843/lib/src/gesture_detector/drag.dart(145,3): error GB23DA612: The superclass, 'OneSequenceGestureRecognizer with DragGestureRecognizerMixin', has no unnamed constructor that takes no arguments.
> 
> Am I doing something wrong?

That's because v7.0.0  update was for the flutter stable channel, not a master channel.
Also, I have updated the fork to fix that issue so now it should work fine with the master channel.

**Comment by Alijaaan** [comment]
Great , Thanks , the problem is solved 💯

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/540#issuecomment-1416720916

**Comment by Mae623** [comment]
> we will fix it after stable

请问那大概是什么时候呢？

**Comment by zmtzawqlp** [comment]
> > we will fix it after stable
> 
> 请问那大概是什么时候呢？

merge this change after this change join flutter stable

**Comment by cpboyd** [comment]
Note `WidgetsBinding.instance.window` is now deprecated as well.
#572 is probably better for this reason (so that we don't face similar build issues at the next Flutter version)

**Comment by zmtzawqlp** [comment]
close with https://github.com/fluttercandies/extended_image/commit/fc1cb041b01e3397a772a4131ccbd9fa3b6c1ef0#diff-fc1c9333b4d84f684b12f4c73cb555ff92446b65dfcb3896b4f6cc24ee60b821

**Pull request closed without merging**
