### PR TITLE
Drag trackpad gestures

### PR DESCRIPTION
**Pull request by moffatman**
Now we have trackpad gestures in stable, I copied the same changes from https://github.com/flutter/flutter/pull/89944

This will allow using trackpad to swipe between pages in the page view.

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
any public api need to add?  these changes are only internal changes?

**Comment by moffatman** [comment]
Only internal change. But if you think we should allow users to enable or disable trackpad use, I can update it with `supportedDevices` parameter on `ExtendedImageGesturePageViewState`

**Comment by zmtzawqlp** [comment]
> ExtendedImageGesturePageVie

ok, thanks, so the user can use trackpad to scroll ExtendedImageGesturePageView, right?

**Comment by moffatman** [comment]
Yeah, after this change, you will be able to use Mac, Linux, Windows, and iPad trackpad to scroll between pages. I just had to copy the change here, since you have a customized gesture recognizer. I need to apply the same changes as in `flutter/flutter`

**Comment by zmtzawqlp** [comment]
thanks for your contribution, i have merge the code from 3.3.8 and refactor them to be more convenience to merge if next time.

**Pull request closed without merging**
