### PR TITLE
Update extended_network_image_provider.dart

### PR DESCRIPTION
**Pull request by ThinkDigitalRepair**
Fixes build errors caused by Flutter 1.5.9-pre.106 update.
Fixes grammar and spelling

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
thank for check spelling，i will do this change.  and i think we should not do some change just for Flutter 1.5.9-pre.106 update, almost users are not in this version.

**Comment by ThinkDigitalRepair** [comment]
It's a cast to the type explicitly, that's all. It should still work on
older versions. I haven't tested it on older versions though

**Comment by zmtzawqlp** [comment]
old version can't build successfully， i have tested it

**Comment by ThinkDigitalRepair** [comment]
Ok. So what will you do? It doesn't build successfully for the new version
without it. The flutter team just updates the package and lists a breaking
change in the changelog. Users still have the option to stay on the
old version Hy using version constraints since that's what it's for.

**Comment by zmtzawqlp** [comment]
codes are base on flutter 1.1.5 (NetworkImage), if any one find some codes are broken,
please fix them base on your flutter version, would't maintain codes for every version.

**Comment by ThinkDigitalRepair** [comment]
I'm sorry, I don't understand

**Comment by zmtzawqlp** [comment]
user can fix broken code by themself, base on the their version .we can't force user to update to lastest version

**Comment by ThinkDigitalRepair** [comment]
The code is in your package. You don't have to force users to use the
newest version. They can stay on the old package version. This is what the
Flutter team did with all their packages when updating to AndroidX. All
users who were not ready stayed on old packages. It's your package, though,
so it's your decision.

**Comment by zmtzawqlp** [comment]
if have any bug fix or new function for extended image in the future, we can't tell user , you must use flutter 1.5.9. i will update this till flutter team make 1.5.9 as stable version, thanks for your suggestion

**Comment by ThinkDigitalRepair** [comment]
Thank you as well

**Comment by ThinkDigitalRepair** [comment]
I'm just going to leave an open issue for others who may come for the same thing. No pressure.

**Pull request closed without merging**
