### PR TITLE
Support custom shape of crop area

### PR DESCRIPTION
**Pull request by masonTool**
Enhancement for:  https://github.com/fluttercandies/extended_image/issues/262

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
This is only for ui，how to you crop the raw image data?

**Comment by masonTool** [comment]
The plugin don't support crop image data directly.   You supply a `cropImageDataWithNativeLibrary` method in your example, but not the plugin.   So I think, the crop action should be done by developer themselves.  According to the state attributes `editAction`

**Comment by BoonJunTan** [comment]
@masonTool can I check does this mean currently we cannot have a circle crop area?

**Comment by zmtzawqlp** [comment]
the ui, you can define by your self by EditorCropLayerPainter, but the data you should handle by yourself

**Comment by masonTool** [comment]
> @masonTool can I check does this mean currently we cannot have a circle crop area?

as developer said, crop data by yourseft.   you paint, you crop.

**Pull request closed without merging**
